/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AssetMonitorInsightList: typeof import('./src/components/asset-monitor/AssetMonitorInsightList.vue')['default']
    AssetMonitorRelationGraph: typeof import('./src/components/asset-monitor/AssetMonitorRelationGraph.vue')['default']
    AssetMonitorRightPanel: typeof import('./src/components/asset-monitor/AssetMonitorRightPanel.vue')['default']
    AssetMonitorSidebar: typeof import('./src/components/asset-monitor/AssetMonitorSidebar.vue')['default']
    AssetMonitorTopPanel: typeof import('./src/components/asset-monitor/AssetMonitorTopPanel.vue')['default']
    CircularProgress: typeof import('./src/components/ecoSignal/CircularProgress.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    InfiniteScroll: typeof import('./src/components/common/InfiniteScroll.vue')['default']
    MainNav: typeof import('./src/components/common/MainNav.vue')['default']
    RadarTopEventsTable: typeof import('./src/components/opportunity-radar/RadarTopEventsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentimentGauge: typeof import('./src/components/ecoSignal/SentimentGauge.vue')['default']
    SignalCard: typeof import('./src/components/ecoSignal/SignalCard.vue')['default']
  }
}
