/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    CircularProgress: typeof import('./src/components/ecoSignal/CircularProgress.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    InfiniteScroll: typeof import('./src/components/common/InfiniteScroll.vue')['default']
    MainNav: typeof import('./src/components/common/MainNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentimentGauge: typeof import('./src/components/ecoSignal/SentimentGauge.vue')['default']
    SignalCard: typeof import('./src/components/ecoSignal/SignalCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
